supergraph:
  listen: 127.0.0.1:4000

include_subgraph_errors:
  all: true

# This requires Enterprise but is the config we can use on serverless
#subscription:
#  mode:
#    passthrough:
#      all:
#        path: /ws

headers:
  all:
    request:
      - propagate:
          matching: .*
