name: merge-to-main

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


env:
  APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
  APOLLO_VCS_COMMIT: ${{ github.event.pull_request.head.sha }}
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy-monolith:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to fly
        run: flyctl deploy --remote-only

  subgraph-comments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH

      - name: Publish subgraph schema
        working-directory: ./subgraphs/comments
        run: |
          rover subgraph publish apollo-media-supergraph@prod \
            --name comments \
            --schema schema.graphql

  subgraph-media:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH

      - name: Publish subgraph schema
        working-directory: ./subgraphs/media
        run: |
          rover subgraph publish apollo-media-supergraph@prod \
            --name media \
            --schema schema.graphql

  subgraph-ratings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH

      - name: Publish subgraph schema
        working-directory: ./subgraphs/ratings
        run: |
          rover subgraph publish apollo-media-supergraph@prod \
            --name ratings \
            --schema schema.graphql

  subgraph-search:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH

      - name: Publish subgraph schema
        working-directory: ./subgraphs/search
        run: |
          rover subgraph publish apollo-media-supergraph@prod \
            --name search \
            --schema schema.graphql

  subgraph-trending:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH

      - name: Publish subgraph schema
        working-directory: ./subgraphs/trending
        run: |
          rover subgraph publish apollo-media-supergraph@prod \
            --name trending \
            --schema schema.graphql

  subgraph-users:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH

      - name: Publish subgraph schema
        working-directory: ./subgraphs/users
        run: |
          rover subgraph publish apollo-media-supergraph@prod \
            --name users \
            --schema schema.graphql

  publish-README:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH

      - name: Publish README
        run: rover readme publish apollo-media-supergraph@prod --file README.md
